wildfly:
  image: 54.85.37.228:5000/wildfly:8.2.0-b33
  container_name: wildfly-py-fixture
  expose:
    - "9990"
    - "9999"
    - "8080"
  ports:
    - "9990:9990"
    - "9999:9999"
    - "8080:8080"
  volumes:
    - /opt/wildfly/domain
  environment:
    JVM_MAX_HEAP: 512m
    DOMAIN_CONTROLLER: "true"
    NUM_SERVERS: 1

test:
  build: .
  links:
    - wildfly
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: py.test

