wildfly:
  image: jboss/wildfly-admin
  container_name: wildfly-py-fixture
  expose:
    - "9990"
    - "9999"
    - "8080"
  ports:
    - "9990:9990"
    - "9999:9999"
    - "8080:8080"
  volumes:
    - /opt/wildfly/domain

test:
  build: .
  links:
    - wildfly
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: py.test

debug:
  build: .
  container_name: debug
  links:
    - wildfly
  volumes:
    - .:/code
    - /var/run/docker.sock:/var/run/docker.sock
  working_dir: /code
  command: sh
