wildfly:
  image: docker.cenx.localnet:5000/wildfly:8.2.0-b33
  container_name: wildfly-py-fixture
  expose:
    - "9990"
    - "9999"
    - "8080"
  ports:
    - "9990:9990"
    - "9999:9999"
    - "8080:8080"
  volumes:
    - /opt/wildfly/domain
  environment:
    JVM_MAX_HEAP: 512m
    DOMAIN_CONTROLLER: "true"
    NUM_SERVERS: 1

wildfly-py:
  build: .
  links:
    - wildfly
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: py.test

wildfly-py-debug:
  build: .
  container_name: wildfly-py-debug
  links:
    - wildfly
  volumes:
    - .:/code
    - /var/run/docker.sock:/var/run/docker.sock
  working_dir: /code
  command: /bin/bash

wildfly-cli:
  image: docker.cenx.localnet:5000/wildfly:8.2.0-b33
  links:
    - wildfly
  command: /opt/wildfly/bin/jboss-cli.sh --controller=wildfly-py-fixture:9990 --connect --user=admin --password=admin
    
    
    