nexus:
  image: sonatype/nexus
  container_name: nexus
  ports:
    - "8081:8081"

wildfly:
  build: ./wildfly
  container_name: wildfly
  expose:
    - "9990"
    - "9999"
    - "8080"
  ports:
    - "9990:9990"
    - "9999:9999"
    - "8080:8080"
  volumes:
    - /opt/wildfly/domain

test:
  build: .
  container_name: test
  links:
    - wildfly
    - nexus
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: py.test

debug:
  build: .
  container_name: debug
  links:
    - wildfly
    - nexus
  volumes:
    - .:/code
    - /var/run/docker.sock:/var/run/docker.sock
  working_dir: /code
  command: sh
